[package]
name = "mindbox"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.9.0", default-features = false, features = [
    "macros",
] }
serde = { version = "1.0", features = ["derive"] }
